default:
  workbench:
    username: !expr Sys.getenv("WORKBENCH_UID")
    password: !expr Sys.getenv("WORKBENCH_PWD")
  dap:
    driver: !expr Sys.getenv("DAP_DRIVER")
    uid: !expr Sys.getenv("DAP_UID")
    pwd: !expr Sys.getenv("DAP_PWD")
    servernode: !expr Sys.getenv("DAP_SERVER")
  bulldrive:
    domain: !expr Sys.getenv("EGNYTER_DOMAIN")
    apikey: !expr Sys.getenv("EGNYTER_APIKEY")
    project_folder: !expr Sys.getenv("BULLDRIVE_PROJECT_FOLDER")
  ods:
    driver: !expr Sys.getenv("ODS_DRIVER")
    uid: !expr Sys.getenv("ODS_UID")
    pwd: !expr Sys.getenv("ODS_PWD")
    server: !expr Sys.getenv("ODS_SERVER")
    port: !expr Sys.getenv("ODS_PORT")
